In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sbn

In [2]:
df = pd.read_csv("311_Dictionary.csv" , header=None,on_bad_lines='skip')

In [3]:
df.columns

Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21],
      dtype='int64')

In [4]:
df = df.iloc[:, :2]
df.columns = ["Field", "Value"]

In [5]:
df = df.apply(lambda col: col.str.strip() if col.dtype == "object" else col)
df.tail()

                             Field Value
12159  Location/Point/Line/Polygon   NaN
12160                       Number   NaN
12161                         Text   NaN
12162   True-False/Checkbox/Binary   NaN
12163                  URL/Website   NaN

In [6]:
df=df.apply(
    lambda col: col.str.replace(r"\s+","",regex=True).str.strip()
    if col.dtype=='object' else col
)

In [7]:
df.shape

(12164, 2)

In [8]:
df.columns

Index(['Field', 'Value'], dtype='str')

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12164 entries, 0 to 12163
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Field   12164 non-null  str
 1   Value   12046 non-null  str
dtypes: str(2)
memory usage: 190.2 KB

In [10]:
df.describe(include='all')

                                                    Field     Value
count                                               12164     12046
unique                                                167       292
top     Department of Housing Preservation and Develop...  Plumbing
freq                                                 6051      1063

In [11]:
df=df.dropna()
df

,Field,Value
1,Dataset Name,311 Service Requests from 2020 to Present
2,Dataset URL,https://data.cityofnewyork.us/Social-Services/...
3,Data Provided by\r\nThe name of the NYC agency...,311
4,Each row is a... \r\nThe unit of analysis/leve...,311 Service Request
5,Publishing Frequency\r\nHow often changed data...,Daily
...,...,...
12046,Every 5 years,Every 5 years
12047,Every 10 years,Every 10 years
12048,Historical data,Historical data
12049,As needed,As needed
12050,To be determined,Not Applicable

In [12]:
df.isnull().sum()

Field    0
Value    0
dtype: int64

In [13]:
df.fillna("Unknown",inplace=True)

,Field,Value
1,Dataset Name,311 Service Requests from 2020 to Present
2,Dataset URL,https://data.cityofnewyork.us/Social-Services/...
3,Data Provided by\r\nThe name of the NYC agency...,311
4,Each row is a... \r\nThe unit of analysis/leve...,311 Service Request
5,Publishing Frequency\r\nHow often changed data...,Daily
...,...,...
12046,Every 5 years,Every 5 years
12047,Every 10 years,Every 10 years
12048,Historical data,Historical data
12049,As needed,As needed
12050,To be determined,Not Applicable

In [14]:
df.drop_duplicates(inplace=True)
df

,Field,Value
1,Dataset Name,311 Service Requests from 2020 to Present
2,Dataset URL,https://data.cityofnewyork.us/Social-Services/...
3,Data Provided by\r\nThe name of the NYC agency...,311
4,Each row is a... \r\nThe unit of analysis/leve...,311 Service Request
5,Publishing Frequency\r\nHow often changed data...,Daily
...,...,...
12046,Every 5 years,Every 5 years
12047,Every 10 years,Every 10 years
12048,Historical data,Historical data
12049,As needed,As needed
12050,To be determined,Not Applicable

In [15]:
df.drop_duplicates(inplace=True)
df

,Field,Value
1,Dataset Name,311 Service Requests from 2020 to Present
2,Dataset URL,https://data.cityofnewyork.us/Social-Services/...
3,Data Provided by\r\nThe name of the NYC agency...,311
4,Each row is a... \r\nThe unit of analysis/leve...,311 Service Request
5,Publishing Frequency\r\nHow often changed data...,Daily
...,...,...
12046,Every 5 years,Every 5 years
12047,Every 10 years,Every 10 years
12048,Historical data,Historical data
12049,As needed,As needed
12050,To be determined,Not Applicable

In [17]:
grouped_df1 = df.groupby("Field")["Value"].sum().reset_index()